// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemInfo.Models.Data;

namespace SystemInfo.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210630160236_AddOnDeleteCasadeBehavior")]
    partial class AddOnDeleteCasadeBehavior
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SystemInfo.Models.Domain.Enterprise", b =>
                {
                    b.Property<string>("RNC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RNC");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("SystemInfo.Models.Domain.SystemSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnterpriseRNC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOperatingSystem64bits")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatingSystemVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessorCount")
                        .HasColumnType("int");

                    b.Property<string>("ProcessorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMemoryInGigaBytes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseRNC");

                    b.ToTable("SystemSpecs");
                });

            modelBuilder.Entity("SystemInfo.Models.Domain.WindowsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SystemSpecsId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SystemSpecsId");

                    b.ToTable("WindowsAccount");
                });

            modelBuilder.Entity("SystemInfo.Models.Domain.SystemSpecs", b =>
                {
                    b.HasOne("SystemInfo.Models.Domain.Enterprise", "Enterprise")
                        .WithMany("SystemSpecs")
                        .HasForeignKey("EnterpriseRNC")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("SystemInfo.Models.Domain.WindowsAccount", b =>
                {
                    b.HasOne("SystemInfo.Models.Domain.SystemSpecs", "SystemSpecs")
                        .WithMany("WindowsAccounts")
                        .HasForeignKey("SystemSpecsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemSpecs");
                });

            modelBuilder.Entity("SystemInfo.Models.Domain.Enterprise", b =>
                {
                    b.Navigation("SystemSpecs");
                });

            modelBuilder.Entity("SystemInfo.Models.Domain.SystemSpecs", b =>
                {
                    b.Navigation("WindowsAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
